name: karaokeparty
description: "Client for the Karaoke-Server."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  animated_list_plus: ^0.5.2
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3
  flutter_constraintlayout: ^1.7.0-stable
  flutter_secure_storage: ^9.0.0
  http: ^1.1.2
  infinite_scroll_pagination: ^4.0.0
  intl: ^0.19.0
  logger: ^2.0.2+1
  rounded_loading_button: ^2.1.0
  skeletonizer: ^0.8.0
  slang: ^3.28.0
  uuid: ^4.2.2
  web_socket_channel: ^2.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1
  slang_flutter: ^3.17.0
  slang_build_runner: ^3.17.0

flutter:
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
